#Port
server:
  port: 4242
#Database connection
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/tyss
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver